language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t fe-udagram-lucasbrogni .
  - docker tag fe-udagram-lucasbrogni lucasbrogni/fe-udagram-lucasbrogni
  - docker login -u "lucasbrogni" -p "$DOCKER_PASSWORD"
  - docker push lucasbrogni/fe-udagram-lucasbrogni
